### ISSUE TITLE
Spelling mistakes on wiki pages

### ISSUE THREAD

**Issue by typable** [unpacked-dev/shortthis-api#9]
Change **"Authentification"** to **"Authentication"**.

The spelling error can be found on the following pages:

- https://github.com/unpacked-dev/shortthis-api/wiki/
- https://github.com/unpacked-dev/shortthis-api/wiki/Authentification

**Comment by unpacked-dev** [comment]
Thanks for contributing! ✌️
Mistake is fixed now.
